// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkNMu5Uae3MHMwVoHnEVEWIltcg4bW9SE',
    appId: '1:117587654364:web:c88ca30514c487a2c9a619',
    messagingSenderId: '117587654364',
    projectId: 'bookmysh-9798e',
    authDomain: 'bookmysh-9798e.firebaseapp.com',
    storageBucket: 'bookmysh-9798e.firebasestorage.app',
    measurementId: 'G-YMZEZ7CJLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCurLKaes-ayeoK3racF5SrlvPv8k0z-Zs',
    appId: '1:117587654364:android:0daa88d297b1f808c9a619',
    messagingSenderId: '117587654364',
    projectId: 'bookmysh-9798e',
    storageBucket: 'bookmysh-9798e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpH5aPSJttepx3VQ_qOpRxt4lJbpnyA-A',
    appId: '1:117587654364:ios:927c25aba71202fdc9a619',
    messagingSenderId: '117587654364',
    projectId: 'bookmysh-9798e',
    storageBucket: 'bookmysh-9798e.firebasestorage.app',
    iosBundleId: 'com.example.bookmysht',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpH5aPSJttepx3VQ_qOpRxt4lJbpnyA-A',
    appId: '1:117587654364:ios:927c25aba71202fdc9a619',
    messagingSenderId: '117587654364',
    projectId: 'bookmysh-9798e',
    storageBucket: 'bookmysh-9798e.firebasestorage.app',
    iosBundleId: 'com.example.bookmysht',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkNMu5Uae3MHMwVoHnEVEWIltcg4bW9SE',
    appId: '1:117587654364:web:1a07a7cc8a1bbee6c9a619',
    messagingSenderId: '117587654364',
    projectId: 'bookmysh-9798e',
    authDomain: 'bookmysh-9798e.firebaseapp.com',
    storageBucket: 'bookmysh-9798e.firebasestorage.app',
    measurementId: 'G-Y2NHVCP3TL',
  );
}
